version: "2.1"
services:
  theme-park:
    image: ghcr.io/themepark-dev/theme.park
    container_name: theme-park
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - TP_URLBASE=themepark #optional
    volumes:
      - /config/theme.park:/config #optional
    ports:
      - 8089:80
      - 4443:443
    restart: unless-stopped